/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Element = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'pageId' : IDL.Text,
  'elementType' : IDL.Text,
  'propsJson' : IDL.Text,
});
export const Page = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'projectId' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createElement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Element],
      [],
    ),
  'createPage' : IDL.Func([IDL.Text, IDL.Text], [Page], []),
  'createProject' : IDL.Func([IDL.Text], [Project], []),
  'deleteElement' : IDL.Func([IDL.Text], [], []),
  'deletePage' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getElements' : IDL.Func([IDL.Text], [IDL.Vec(Element)], ['query']),
  'getMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getPages' : IDL.Func([IDL.Text], [IDL.Vec(Page)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderElements' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateElement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateProjectName' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Element = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'pageId' : IDL.Text,
    'elementType' : IDL.Text,
    'propsJson' : IDL.Text,
  });
  const Page = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'projectId' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createElement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Element],
        [],
      ),
    'createPage' : IDL.Func([IDL.Text, IDL.Text], [Page], []),
    'createProject' : IDL.Func([IDL.Text], [Project], []),
    'deleteElement' : IDL.Func([IDL.Text], [], []),
    'deletePage' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getElements' : IDL.Func([IDL.Text], [IDL.Vec(Element)], ['query']),
    'getMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getPages' : IDL.Func([IDL.Text], [IDL.Vec(Page)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderElements' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateElement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateProjectName' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };