/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Element {
  'id' : string,
  'order' : bigint,
  'pageId' : string,
  'elementType' : string,
  'propsJson' : string,
}
export interface Page {
  'id' : string,
  'order' : bigint,
  'name' : string,
  'projectId' : string,
}
export interface Project {
  'id' : string,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createElement' : ActorMethod<[string, string, string, bigint], Element>,
  'createPage' : ActorMethod<[string, string], Page>,
  'createProject' : ActorMethod<[string], Project>,
  'deleteElement' : ActorMethod<[string], undefined>,
  'deletePage' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getElements' : ActorMethod<[string], Array<Element>>,
  'getMyProjects' : ActorMethod<[], Array<Project>>,
  'getPages' : ActorMethod<[string], Array<Page>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderElements' : ActorMethod<[string, Array<string>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateElement' : ActorMethod<[string, string], undefined>,
  'updatePage' : ActorMethod<[string, string], undefined>,
  'updateProjectName' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];